export const _partsCategory = [
  {
    category: 'Engine',
    icon: 'engine',
    description: "Parts related to the car's engine system.",
    subcategories: [
      'Engine Assembly',
      'Cylinder Head',
      'Engine Block',
      'Pistons',
      'Piston Rings',
      'Crankshaft',
      'Camshaft',
      'Timing Belt/Chain',
      'Timing Components',
      'Oil Pump',
      'Oil Filter',
      'Air Filter',
      'Fuel Pump',
      'Fuel Injectors',
      'Ignition Coil',
      'Spark Plugs',
      'Engine Mounts',
      'Valve Cover',
      'Throttle Body',
      'EGR Valve',
      'PCV Valve',
      // ---------- custom -------------
      'AIR CLEANER AND ENGINE CHARGING',
      'ENGINE',
      'ENGINE LUBRICATION',
      'ENGINE SUSPENSION',
      'ENGINE TIMING',
      'SHEET METAL PARTS',
    ],
  },
  {
    category: 'Transmission',
    icon: 'transmission',
    description: "Parts related to the car's transmission system.",
    subcategories: [
      'Transmission Assembly',
      'Transmission Fluid',
      'Transmission Filter',
      'Clutch Kit',
      'Clutch Slave Cylinder',
      'Flywheel',
      'Torque Converter',
      'Axle Shaft',
      'CV Joint',
      'Driveshaft',
      'Shift Solenoid',

      'AUTOMATIC TRANSMISSION',
      'MB AUTOMATIC TRANSMISSION',
      'MB PARTS',
      'PROPELLER SHAFT',
    ],
  },
  {
    category: 'Brakes',
    icon: 'brakes',
    description: "Parts related to the car's braking system.",
    subcategories: [
      'Brake Pads',
      'Brake Discs/Rotors',
      'Brake Calipers',
      'Brake Master Cylinder',
      'Brake Lines/Hoses',
      'Brake Fluid',
      'Brake Booster',
      'ABS Sensor',
      'Parking Brake Cable',

      'BRAKES',
      'SERVICE PARTS',
    ],
  },
  {
    category: 'Suspension',
    icon: 'suspension',
    description: "Parts related to the car's suspension system.",
    subcategories: [
      'Shock Absorbers',
      'Struts',
      'Coil Springs',
      'Control Arms',
      'Sway Bar Links',
      'Ball Joints',
      'Tie Rod Ends',
      'Wheel Bearings',
      'Stabilizer Bar',
      'Air Suspension Components',

      'SPRINGS,​SUSPENSION AND HYDRAULICS',
      'SUSPENSION',
    ],
  },
  {
    category: 'Electrical',
    icon: 'electrical',
    description: "Parts related to the car's electrical system.",
    subcategories: [
      'Battery',
      'Alternator',
      'Starter Motor',
      'Ignition Switch',
      'Ignition Coil',
      'Spark Plug Wires',
      'Distributor',
      'Sensors (MAP, MAF, O2, etc.)',
      'Relays',
      'Fuses',
      'Wiring Harness',
      'Headlights',
      'Tail Lights',
      'Turn Signal Switch',
      'Window Regulator/Motor',
      'Power Window Switch',

      'BATTERY',
      'ELEC',
      'ELECTRICAL EQUIPMENT AND INSTRUMENTS',
      'ELECTRICAL SYSTEM',
      'ENGINE ELECTRICAL EQUIPMENT',
    ],
  },
  {
    category: 'Cooling',
    icon: 'cooling',
    description: "Parts related to the car's cooling system.",
    subcategories: [
      'Radiator',
      'Water Pump',
      'Thermostat',
      'Coolant',
      'Cooling Fan',
      'Radiator Cap',
      'Radiator Hose',
      'Expansion Tank',
      'Heater Core',
      'Thermostat Housing',

      'COOLER',
      'COOLING/AUXILIARY HEATING',
      'ENGINE COOLING',
      'FANS',
      'HEATING AND VENTILATION',
      'POWER STEERING PUMP, AC COMPRESSOR',
      'RADIATOR',
    ],
  },
  {
    category: 'Exhaust',
    icon: 'exhaust',
    description: "Parts related to the car's exhaust system.",
    subcategories: [
      'Exhaust Manifold',
      'Catalytic Converter',
      'Muffler',
      'Exhaust Pipe',
      'Oxygen Sensor',
      'Exhaust Gaskets',
      'EGR Valve',

      'CHASSIS SHEET METAL / AIR INTAKE',
      'EXHAUST SYSTEM',
      'INTAKE AND EXHAUST MANIFOLDS',
    ],
  },
  {
    category: 'Filters',
    icon: 'filters',
    description: "Various filters for the car's systems.",
    subcategories: [
      'Engine Oil Filter',
      'Air Filter',
      'Fuel Filter',
      'Cabin Air Filter',
      'Transmission Filter',
      'Oil Separator/Catch Can',

      'OIL  AND LUBRICANTS',
      'OIL AND ACCESSORIES',
      'PANELLING',
    ],
  },
  {
    category: 'Interior',
    icon: 'interior',
    description: "Parts related to the car's interior.",
    subcategories: [
      'Floor Mats',
      'Seat Covers',
      'Steering Wheel Cover',
      'Dashboard Accessories',
      'Car Audio System',
      'Seat Belts',
      'Door Panels/Trim',
      'Window Regulator/Motor',
      'Power Window Switch',
      'Interior Lights',
      'Cup Holders',
      'Center Console',
      'Instrument Cluster',
      'Shift Knob',

      'INTERIOR',
    ],
  },
  {
    category: 'Exterior',
    icon: 'exterior',
    description: "Parts related to the car's exterior.",
    subcategories: [
      'Car Body Parts',
      'Headlights',
      'Tail Lights',
      'Turn Signal Lights',
      'Fog Lights',
      'Side Mirrors',
      'Door Handles',
      'Window Regulator/Motor',
      'Power Window Switch',
      'Windshield',
      'Windshield Wipers',
      'Grilles',
      'Bumpers',
      'Fenders',
      'Hoods',
      'Trunk/Hatch',

      'BODY KIT',
      'COWL,​FRONT PANEL',
      'DOORS',
      'FENDER',
      'FRONT DOORS',
      'FRONT-END ASSEMBLY, FRONT PANEL',
      'REAR DOORS',
      'SIDE PANELS',
      'SLIDING ROOF',
      'SUBFRAME',
      'SUBSTRUCTURE',
      'TRANSFER CASE',
      'TRUNK LID',
      'TRUNKS AND CASES',
      'WINDOWS',
      'WINDSHIELD WASHER,EMERGENCY EQUIPMT',
    ],
  },
  // {
  //   category: 'Air Conditioning',
  //   icon: 'air-conditioning',
  //   description: "Parts related to the car's air conditioning system.",
  //   subcategories: [
  //     'A/C Compressor',
  //     'A/C Condenser',
  //     'A/C Evaporator',
  //     'A/C Expansion Valve',
  //     'A/C Receiver Drier',
  //     'A/C Blower Motor',
  //     'A/C Control Module',
  //     'A/C Pressure Switch',
  //   ],
  // },
  {
    category: 'Accessories',
    icon: 'air-conditioning',
    description: "Parts related to the car's air conditioning system.",
    subcategories: [
      'ACCESSORIES',
      'ATTACHMENT PARTS',
      'ATTACHMENT PARTS FOR UNITS',
      'ATTACHMENT/BODY PARTS',
    ],
  },
  {
    category: 'Fuel System',
    icon: 'fuel',
    description: "Parts related to the car's fuel system.",
    subcategories: [
      'Fuel Pump',
      'Fuel Filter',
      'Fuel Injector',
      'Fuel Tank',
      'Fuel Pressure Regulator',
      'Throttle Body',
      'Fuel Cap',

      'FUEL INJECTION',
      'FUEL SYSTEM',
    ],
  },
  {
    category: 'Steering',
    icon: 'steering',
    description: "Parts related to the car's steering system.",
    subcategories: [
      'Steering Rack',
      'Power Steering Pump',
      'Power Steering Hose',
      'Steering Column',
      'Steering Wheel',
      'Tie Rod End',
      'Pitman Arm',
      'Idler Arm',

      'FRONT AXLE',
      'STEERING',
    ],
  },
  {
    category: 'Wheels',
    icon: 'wheels',
    description: "Parts related to the car's wheels and tires.",
    subcategories: [
      'Tires',
      'Wheels/Rims',
      'Wheel Bearings',
      'Wheel Hub',
      'Tire Pressure Monitoring System (TPMS) Sensor',
      'Spare Tire',
      'Wheel Lug Nuts',
      'Wheel Locks',
      'Wheel Studs',

      'COVERING AND LINING',
      'REAR AXLE',
      'WHEELS',
    ],
  },
];
